// Code generated by mockery v2.44.1. DO NOT EDIT.

package orders

import (
	context "context"

	models "github.com/moguchev/microservices_courcse/orders_management_system/internal/app/models"
	mock "github.com/stretchr/testify/mock"
)

// MockOrdersRepository is an autogenerated mock type for the OrdersRepository type
type MockOrdersRepository struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *MockOrdersRepository) CreateOrder(ctx context.Context, order *models.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOrders provides a mock function with given fields: ctx, order
func (_m *MockOrdersRepository) FindOrders(ctx context.Context, order Filter) ([]*models.Order, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for FindOrders")
	}

	var r0 []*models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Filter) ([]*models.Order, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Filter) []*models.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, Filter) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockOrdersRepository creates a new instance of MockOrdersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrdersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrdersRepository {
	mock := &MockOrdersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
