apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: app
spec:
  type: ClusterIP
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: app
  ports:
    - name: http
      protocol: TCP
      port: 80 # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
      targetPort: 8080 # Порт контейнера, на котором доступно приложение.
    - name: grpc
      protocol: TCP
      port: 82 # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
      targetPort: 8082 # Порт контейнера, на котором доступно приложение.